### ISSUE TITLE
install das not work

### ISSUE THREAD

**Issue by zorg-iris** [Elao/ElaoBrowserDetectorBundle#4]
hi
just try to install your bundle on symfony 2.6, and it das not work. 

```
Fatal error: Class 'Elao\BrowserDetectorBundle\ElaoBrowserDetectorBundle' not found in D:\Programmation\Web\root_www\neo.app\app\AppKernel.php on line 66
```
of cause dont ask if i deed register in AppKermel ;-)
thank

**Comment by zorg-iris** [comment]
up up up ...

**Comment by Tom32i** [comment]
I'm working on it right now.

**Comment by Tom32i** [comment]
Hello, the new release `1.1.2` should fix all your problems.

I'll wait for your confirmation before closing the issue.

**Comment by zorg-iris** [comment]
hi less probleme to install.
but 
```
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call method "setUserAgent" on class "Elao\BrowserDetector\BrowserDetector"." at D:\Programmation\Web\root_www\neo.app\vendor\elao\browser-detector-bundle\EventListener\RequestListener.php line 43 
```
thank

**Comment by zorg-iris** [comment]
hi where is that you can find this 
```   
$this->browserDetector->setUserAgent($event->getRequest()->headers->get('user-agent'));
```
in service```browserDetector``` ```setUserAgent``` das not even exist! maybe you want to user this ```createBrowserFromUserAgent```

**Comment by Tom32i** [comment]
No, the https://github.com/Elao/ElaoBrowserDetector has been updated to follow these changes.
It has a setUserAgent method now.

Can you try a: `composer update elao/browser-detector` ?

**Comment by zorg-iris** [comment]
Hi, thank i have update and no bug, excepte : 

![2015-01-25_19-23-17](https://cloud.githubusercontent.com/assets/2655228/5892222/3bba5354-a4c8-11e4-9991-4498b823e6ed.png)

the resultat is 
![2015-01-25_19-25-34](https://cloud.githubusercontent.com/assets/2655228/5892227/4ec1f9e8-a4c8-11e4-8732-83b3505a1e94.png)

strange no !!

**Comment by zorg-iris** [comment]
no idear?

**Comment by benji07** [comment]
@zorg-iris did you change your php.ini to enable browscap ? (http://php.net/manual/en/function.get-browser.php)

**Comment by zorg-iris** [comment]
Hi, i deed not this yet. ok i will try on my local php server, but how i do this on production server ? i dont have acces to php.ini.
Thank's

**Comment by benji07** [comment]
Unfortunatly you need to change the php.ini file. But we are thinking of using the https://github.com/piwik/device-detector component instead of browscap

**Comment by xorgxx** [comment]
Very good idear. simce that must more possibility with this device-detector !!! 

so for my project i have to take out your bundle, hope that your new thinking will be stable soon.
thank
