### ISSUE TITLE
add config to redirect incompatible browsers 

### ISSUE THREAD

**Issue by ghost** [Elao/ElaoBrowserDetectorBundle#7]
Please add:
- a configuration option like "incompatible_redirect" which receives a route. All incompatible browsers are redirected to this route.
- a route and a template in different languages which explains why the user has been redirected with links to browser download options.
- make the template easily stylable

**Comment by benji07** [comment]
May be you can create a PR with this feature. with just a configuration value (the route name to let the user define his own template)
